# Generated by Django 3.2.9 on 2021-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='post.Category'),
        ),
    ]
