# Generated by Django 3.2.9 on 2021-12-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
