# Generated by Django 3.2.9 on 2021-12-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20211208_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
