# Generated by Django 4.0 on 2021-12-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='statu',
        ),
        migrations.AddField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('PAYED', 'PAYED'), ('NOT_PAYED', 'NOT_PAYED')], default='NOT_PAYED', max_length=9),
        ),
    ]
