# Generated by Django 4.0 on 2021-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=56)),
                ('address', models.CharField(max_length=256)),
                ('code', models.PositiveIntegerField()),
                ('is_celler', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
