# Generated by Django 4.0 on 2021-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.BigIntegerField(max_length=56),
        ),
    ]
